---
language: "python"
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
    - python: "3.6"
install:
  - pip install .
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - pytest -vv --cov=protontricks --cov-report term --cov-report xml tests
after_success:
  - coveralls
